projects:
  addEmployee:
    schemaPath: src/graphql/schema.json
    includes:
      - src/services/addEmployee.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
